gglanguage: emacs-lisp
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
before_install:
  - if [ "$EMACS" = "emacs24" ]; then
    sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq emacs24 emacs24-el texinfo;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
    sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq
    emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot texinfo;
    fi
script:
  rake install_for_bash