(eval-after-load "auto-complete-config"
  '(progn
     (add-to-list 'ac-dictionary-directories
		  (my-setup-abs-path "el-get/auto-complete/dict/"))
     (ac-config-default)
     (ac-set-trigger-key "TAB")
     (setq ac-ignore-case t)
     (setq ac-auto-start t)
     (ac-flyspell-workaround)
     (setq ac-use-comphist t)
     (global-auto-complete-mode t)
     (setq ac-use-menu-map t)
     (setq ac-use-fuzzy t)
     ;  (setq ac-auto-start 3)
     ;; (setq ac-quick-help-delay 1)
     ;; (setq ac-auto-show-menu 100)
     ;; (setq ac-candidate-limit 10)
     (setq-default ac-sources '(ac-source-yasnippet ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers))
     (add-hook 'emacs-lisp-mode-hook 'ac-emacs-lisp-mode-setup)
     (add-hook 'ruby-mode-hook 'ac-ruby-mode-setup)
     (add-hook 'auto-complete-mode-hook 'ac-common-setup)
     (add-to-list 'ac-modes 'objc-mode)
     ))
(require 'auto-complete-config)
