(global-git-gutter-mode t)
(setq git-gutter:separator-sign "|")
(set-face-foreground 'git-gutter:separator "yellow")
(define-key global-map (kbd "C-x v =") 'git-gutter:popup-hunk)
(define-key global-map (kbd "C-x R") 'git-gutter:revert-hunk)
