(require 'popwin)
(setq popwin:close-popup-window-timer-interval 0.05)
(setq display-buffer-function 'popwin:display-buffer)
(push '("*auto-async-byte-compile*" :height 14 :position bottom :noselect t) popwin:special-display-config)
(push '(" *auto-async-byte-compile*" :height 14 :position bottom :noselect t) popwin:special-display-config)
(push '("  *auto-async-byte-compile*" :height 14 :position bottom :noselect t) popwin:special-display-config)
(push '(" *Compile-Log*" :height 14 :position bottom :noselect t) popwin:special-display-config)
(push '("*Compile-Log*" :height 14 :position bottom :noselect t) popwin:special-display-config)
(push '("*VC-log*" :height 10 :position bottom) popwin:special-display-config)
(push '("*Backtrace*" :height 10 :position bottom :noselect t) popwin:special-display-config)
(push '("*scratch*") popwin:special-display-config)
(push '(dired-mode :position bottom) popwin:special-display-config) ; dired-jump-other-window (C-x 4 C-j)
(push '("*Warnings*") popwin:special-display-config)
(push '("*Remember*" :height 30 :position bottom) popwin:special-display-config)
(push '("*Process List*" :height 10 :position bottom :noselect t) popwin:special-display-config)
(push '("*git-gutter:diff*" :height 10 :position bottom :noselect 1) popwin:special-display-config)
(push '("*quickrun*" :height 10 :position bottom :noselect 1) popwin:special-display-config)
(push '("*el-get packages*" :position bottom) popwin:special-display-config)
(push '("*Selection Ring: `kill-ring'*" :position right) popwin:special-display-config)
(push '("*motion-rake*" :position bottom :height 10) popwin:special-display-config)
(push '("*Bundler*" :position bottom :height 10) popwin:special-display-config)
