;; (eval-after-load "migemo"
;;   '(progn
;;     (setq migemo-options '("-q" "--emacs"))
;;     (setq migemo-command "cmigemo")
;;     (setq migemo-dictionary "/usr/local/share/migemo/utf-8/migemo-dict")
;;     (setq migemo-user-dictionary nil)
;;     (setq migemo-regex-dictionary nil)
;;     (setq migemo-coding-system 'utf-8-unix)
;;     ;; (load-library "migemo")
;;     (migemo-init)
;;     (set-process-query-on-exit-flag migemo-process nil)
;;     (setq moccur-use-migemo t)))
(require 'migemo)
(setq migemo-options '("-q" "--emacs"))
(setq migemo-command "cmigemo")
(setq migemo-dictionary "/usr/local/share/migemo/utf-8/migemo-dict")
(setq migemo-user-dictionary nil)
(setq migemo-regex-dictionary nil)
(setq migemo-coding-system 'utf-8-unix)
;; (load-library "migemo")
(migemo-init)
(set-process-query-on-exit-flag migemo-process nil)
(setq moccur-use-migemo t)
