(add-to-list 'auto-mode-alist '("\\.js$" . js3-mode))
(defun my-js3-mode-hook ()
  (setq js3-indent-level 4)
  (setq js3-consistent-level-indent-inner-bracket t)
  (setq js3-paren-indent-offset 0)
  (setq js3-expr-indent-offset 0)
  (setq js3-paren-indent-offset 0)
  (setq js3-square-indent-offset 0)
  (setq js3-curly-indent-offset 0)
  (require 'flymake-jshint)
  (flymake-mode))

(add-hook 'js3-mode-hook 'my-js3-mode-hook)
